<?php

/**
 * World country list — ISO code, international dial code, Arabic & English names.
 * Used for the phone country-code selector and the "country of residence" field
 * on the front-end booking / online-consultation forms.
 */
return [
    ['iso' => 'JO', 'dial' => '+962', 'name_ar' => 'الأردن', 'name_en' => 'Jordan'],
    ['iso' => 'SA', 'dial' => '+966', 'name_ar' => 'السعودية', 'name_en' => 'Saudi Arabia'],
    ['iso' => 'AE', 'dial' => '+971', 'name_ar' => 'الإمارات', 'name_en' => 'United Arab Emirates'],
    ['iso' => 'KW', 'dial' => '+965', 'name_ar' => 'الكويت', 'name_en' => 'Kuwait'],
    ['iso' => 'QA', 'dial' => '+974', 'name_ar' => 'قطر', 'name_en' => 'Qatar'],
    ['iso' => 'BH', 'dial' => '+973', 'name_ar' => 'البحرين', 'name_en' => 'Bahrain'],
    ['iso' => 'OM', 'dial' => '+968', 'name_ar' => 'عُمان', 'name_en' => 'Oman'],
    ['iso' => 'IQ', 'dial' => '+964', 'name_ar' => 'العراق', 'name_en' => 'Iraq'],
    ['iso' => 'SY', 'dial' => '+963', 'name_ar' => 'سوريا', 'name_en' => 'Syria'],
    ['iso' => 'LB', 'dial' => '+961', 'name_ar' => 'لبنان', 'name_en' => 'Lebanon'],
    ['iso' => 'PS', 'dial' => '+970', 'name_ar' => 'فلسطين', 'name_en' => 'Palestine'],
    ['iso' => 'YE', 'dial' => '+967', 'name_ar' => 'اليمن', 'name_en' => 'Yemen'],
    ['iso' => 'EG', 'dial' => '+20', 'name_ar' => 'مصر', 'name_en' => 'Egypt'],
    ['iso' => 'LY', 'dial' => '+218', 'name_ar' => 'ليبيا', 'name_en' => 'Libya'],
    ['iso' => 'TN', 'dial' => '+216', 'name_ar' => 'تونس', 'name_en' => 'Tunisia'],
    ['iso' => 'DZ', 'dial' => '+213', 'name_ar' => 'الجزائر', 'name_en' => 'Algeria'],
    ['iso' => 'MA', 'dial' => '+212', 'name_ar' => 'المغرب', 'name_en' => 'Morocco'],
    ['iso' => 'SD', 'dial' => '+249', 'name_ar' => 'السودان', 'name_en' => 'Sudan'],
    ['iso' => 'SO', 'dial' => '+252', 'name_ar' => 'الصومال', 'name_en' => 'Somalia'],
    ['iso' => 'DJ', 'dial' => '+253', 'name_ar' => 'جيبوتي', 'name_en' => 'Djibouti'],
    ['iso' => 'MR', 'dial' => '+222', 'name_ar' => 'موريتانيا', 'name_en' => 'Mauritania'],
    ['iso' => 'KM', 'dial' => '+269', 'name_ar' => 'جزر القمر', 'name_en' => 'Comoros'],
    ['iso' => 'TR', 'dial' => '+90', 'name_ar' => 'تركيا', 'name_en' => 'Turkey'],
    ['iso' => 'IR', 'dial' => '+98', 'name_ar' => 'إيران', 'name_en' => 'Iran'],
    ['iso' => 'US', 'dial' => '+1', 'name_ar' => 'الولايات المتحدة', 'name_en' => 'United States'],
    ['iso' => 'CA', 'dial' => '+1', 'name_ar' => 'كندا', 'name_en' => 'Canada'],
    ['iso' => 'GB', 'dial' => '+44', 'name_ar' => 'المملكة المتحدة', 'name_en' => 'United Kingdom'],
    ['iso' => 'IE', 'dial' => '+353', 'name_ar' => 'أيرلندا', 'name_en' => 'Ireland'],
    ['iso' => 'FR', 'dial' => '+33', 'name_ar' => 'فرنسا', 'name_en' => 'France'],
    ['iso' => 'DE', 'dial' => '+49', 'name_ar' => 'ألمانيا', 'name_en' => 'Germany'],
    ['iso' => 'ES', 'dial' => '+34', 'name_ar' => 'إسبانيا', 'name_en' => 'Spain'],
    ['iso' => 'PT', 'dial' => '+351', 'name_ar' => 'البرتغال', 'name_en' => 'Portugal'],
    ['iso' => 'IT', 'dial' => '+39', 'name_ar' => 'إيطاليا', 'name_en' => 'Italy'],
    ['iso' => 'NL', 'dial' => '+31', 'name_ar' => 'هولندا', 'name_en' => 'Netherlands'],
    ['iso' => 'BE', 'dial' => '+32', 'name_ar' => 'بلجيكا', 'name_en' => 'Belgium'],
    ['iso' => 'LU', 'dial' => '+352', 'name_ar' => 'لوكسمبورغ', 'name_en' => 'Luxembourg'],
    ['iso' => 'CH', 'dial' => '+41', 'name_ar' => 'سويسرا', 'name_en' => 'Switzerland'],
    ['iso' => 'AT', 'dial' => '+43', 'name_ar' => 'النمسا', 'name_en' => 'Austria'],
    ['iso' => 'SE', 'dial' => '+46', 'name_ar' => 'السويد', 'name_en' => 'Sweden'],
    ['iso' => 'NO', 'dial' => '+47', 'name_ar' => 'النرويج', 'name_en' => 'Norway'],
    ['iso' => 'DK', 'dial' => '+45', 'name_ar' => 'الدنمارك', 'name_en' => 'Denmark'],
    ['iso' => 'FI', 'dial' => '+358', 'name_ar' => 'فنلندا', 'name_en' => 'Finland'],
    ['iso' => 'IS', 'dial' => '+354', 'name_ar' => 'آيسلندا', 'name_en' => 'Iceland'],
    ['iso' => 'PL', 'dial' => '+48', 'name_ar' => 'بولندا', 'name_en' => 'Poland'],
    ['iso' => 'CZ', 'dial' => '+420', 'name_ar' => 'التشيك', 'name_en' => 'Czech Republic'],
    ['iso' => 'SK', 'dial' => '+421', 'name_ar' => 'سلوفاكيا', 'name_en' => 'Slovakia'],
    ['iso' => 'HU', 'dial' => '+36', 'name_ar' => 'المجر', 'name_en' => 'Hungary'],
    ['iso' => 'RO', 'dial' => '+40', 'name_ar' => 'رومانيا', 'name_en' => 'Romania'],
    ['iso' => 'BG', 'dial' => '+359', 'name_ar' => 'بلغاريا', 'name_en' => 'Bulgaria'],
    ['iso' => 'GR', 'dial' => '+30', 'name_ar' => 'اليونان', 'name_en' => 'Greece'],
    ['iso' => 'CY', 'dial' => '+357', 'name_ar' => 'قبرص', 'name_en' => 'Cyprus'],
    ['iso' => 'MT', 'dial' => '+356', 'name_ar' => 'مالطا', 'name_en' => 'Malta'],
    ['iso' => 'HR', 'dial' => '+385', 'name_ar' => 'كرواتيا', 'name_en' => 'Croatia'],
    ['iso' => 'SI', 'dial' => '+386', 'name_ar' => 'سلوفينيا', 'name_en' => 'Slovenia'],
    ['iso' => 'RS', 'dial' => '+381', 'name_ar' => 'صربيا', 'name_en' => 'Serbia'],
    ['iso' => 'BA', 'dial' => '+387', 'name_ar' => 'البوسنة والهرسك', 'name_en' => 'Bosnia and Herzegovina'],
    ['iso' => 'ME', 'dial' => '+382', 'name_ar' => 'الجبل الأسود', 'name_en' => 'Montenegro'],
    ['iso' => 'MK', 'dial' => '+389', 'name_ar' => 'مقدونيا الشمالية', 'name_en' => 'North Macedonia'],
    ['iso' => 'AL', 'dial' => '+355', 'name_ar' => 'ألبانيا', 'name_en' => 'Albania'],
    ['iso' => 'XK', 'dial' => '+383', 'name_ar' => 'كوسوفو', 'name_en' => 'Kosovo'],
    ['iso' => 'UA', 'dial' => '+380', 'name_ar' => 'أوكرانيا', 'name_en' => 'Ukraine'],
    ['iso' => 'BY', 'dial' => '+375', 'name_ar' => 'بيلاروسيا', 'name_en' => 'Belarus'],
    ['iso' => 'MD', 'dial' => '+373', 'name_ar' => 'مولدوفا', 'name_en' => 'Moldova'],
    ['iso' => 'RU', 'dial' => '+7', 'name_ar' => 'روسيا', 'name_en' => 'Russia'],
    ['iso' => 'EE', 'dial' => '+372', 'name_ar' => 'إستونيا', 'name_en' => 'Estonia'],
    ['iso' => 'LV', 'dial' => '+371', 'name_ar' => 'لاتفيا', 'name_en' => 'Latvia'],
    ['iso' => 'LT', 'dial' => '+370', 'name_ar' => 'ليتوانيا', 'name_en' => 'Lithuania'],
    ['iso' => 'GE', 'dial' => '+995', 'name_ar' => 'جورجيا', 'name_en' => 'Georgia'],
    ['iso' => 'AM', 'dial' => '+374', 'name_ar' => 'أرمينيا', 'name_en' => 'Armenia'],
    ['iso' => 'AZ', 'dial' => '+994', 'name_ar' => 'أذربيجان', 'name_en' => 'Azerbaijan'],
    ['iso' => 'KZ', 'dial' => '+7', 'name_ar' => 'كازاخستان', 'name_en' => 'Kazakhstan'],
    ['iso' => 'UZ', 'dial' => '+998', 'name_ar' => 'أوزبكستان', 'name_en' => 'Uzbekistan'],
    ['iso' => 'TM', 'dial' => '+993', 'name_ar' => 'تركمانستان', 'name_en' => 'Turkmenistan'],
    ['iso' => 'TJ', 'dial' => '+992', 'name_ar' => 'طاجيكستان', 'name_en' => 'Tajikistan'],
    ['iso' => 'KG', 'dial' => '+996', 'name_ar' => 'قيرغيزستان', 'name_en' => 'Kyrgyzstan'],
    ['iso' => 'AF', 'dial' => '+93', 'name_ar' => 'أفغانستان', 'name_en' => 'Afghanistan'],
    ['iso' => 'PK', 'dial' => '+92', 'name_ar' => 'باكستان', 'name_en' => 'Pakistan'],
    ['iso' => 'IN', 'dial' => '+91', 'name_ar' => 'الهند', 'name_en' => 'India'],
    ['iso' => 'BD', 'dial' => '+880', 'name_ar' => 'بنغلاديش', 'name_en' => 'Bangladesh'],
    ['iso' => 'LK', 'dial' => '+94', 'name_ar' => 'سريلانكا', 'name_en' => 'Sri Lanka'],
    ['iso' => 'NP', 'dial' => '+977', 'name_ar' => 'نيبال', 'name_en' => 'Nepal'],
    ['iso' => 'BT', 'dial' => '+975', 'name_ar' => 'بوتان', 'name_en' => 'Bhutan'],
    ['iso' => 'MV', 'dial' => '+960', 'name_ar' => 'المالديف', 'name_en' => 'Maldives'],
    ['iso' => 'MM', 'dial' => '+95', 'name_ar' => 'ميانمار', 'name_en' => 'Myanmar'],
    ['iso' => 'TH', 'dial' => '+66', 'name_ar' => 'تايلاند', 'name_en' => 'Thailand'],
    ['iso' => 'LA', 'dial' => '+856', 'name_ar' => 'لاوس', 'name_en' => 'Laos'],
    ['iso' => 'KH', 'dial' => '+855', 'name_ar' => 'كمبوديا', 'name_en' => 'Cambodia'],
    ['iso' => 'VN', 'dial' => '+84', 'name_ar' => 'فيتنام', 'name_en' => 'Vietnam'],
    ['iso' => 'MY', 'dial' => '+60', 'name_ar' => 'ماليزيا', 'name_en' => 'Malaysia'],
    ['iso' => 'SG', 'dial' => '+65', 'name_ar' => 'سنغافورة', 'name_en' => 'Singapore'],
    ['iso' => 'ID', 'dial' => '+62', 'name_ar' => 'إندونيسيا', 'name_en' => 'Indonesia'],
    ['iso' => 'BN', 'dial' => '+673', 'name_ar' => 'بروناي', 'name_en' => 'Brunei'],
    ['iso' => 'PH', 'dial' => '+63', 'name_ar' => 'الفلبين', 'name_en' => 'Philippines'],
    ['iso' => 'TL', 'dial' => '+670', 'name_ar' => 'تيمور الشرقية', 'name_en' => 'Timor-Leste'],
    ['iso' => 'CN', 'dial' => '+86', 'name_ar' => 'الصين', 'name_en' => 'China'],
    ['iso' => 'HK', 'dial' => '+852', 'name_ar' => 'هونغ كونغ', 'name_en' => 'Hong Kong'],
    ['iso' => 'MO', 'dial' => '+853', 'name_ar' => 'ماكاو', 'name_en' => 'Macau'],
    ['iso' => 'TW', 'dial' => '+886', 'name_ar' => 'تايوان', 'name_en' => 'Taiwan'],
    ['iso' => 'JP', 'dial' => '+81', 'name_ar' => 'اليابان', 'name_en' => 'Japan'],
    ['iso' => 'KR', 'dial' => '+82', 'name_ar' => 'كوريا الجنوبية', 'name_en' => 'South Korea'],
    ['iso' => 'KP', 'dial' => '+850', 'name_ar' => 'كوريا الشمالية', 'name_en' => 'North Korea'],
    ['iso' => 'MN', 'dial' => '+976', 'name_ar' => 'منغوليا', 'name_en' => 'Mongolia'],
    ['iso' => 'AU', 'dial' => '+61', 'name_ar' => 'أستراليا', 'name_en' => 'Australia'],
    ['iso' => 'NZ', 'dial' => '+64', 'name_ar' => 'نيوزيلندا', 'name_en' => 'New Zealand'],
    ['iso' => 'FJ', 'dial' => '+679', 'name_ar' => 'فيجي', 'name_en' => 'Fiji'],
    ['iso' => 'PG', 'dial' => '+675', 'name_ar' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea'],
    ['iso' => 'ZA', 'dial' => '+27', 'name_ar' => 'جنوب أفريقيا', 'name_en' => 'South Africa'],
    ['iso' => 'NG', 'dial' => '+234', 'name_ar' => 'نيجيريا', 'name_en' => 'Nigeria'],
    ['iso' => 'GH', 'dial' => '+233', 'name_ar' => 'غانا', 'name_en' => 'Ghana'],
    ['iso' => 'KE', 'dial' => '+254', 'name_ar' => 'كينيا', 'name_en' => 'Kenya'],
    ['iso' => 'ET', 'dial' => '+251', 'name_ar' => 'إثيوبيا', 'name_en' => 'Ethiopia'],
    ['iso' => 'TZ', 'dial' => '+255', 'name_ar' => 'تنزانيا', 'name_en' => 'Tanzania'],
    ['iso' => 'UG', 'dial' => '+256', 'name_ar' => 'أوغندا', 'name_en' => 'Uganda'],
    ['iso' => 'RW', 'dial' => '+250', 'name_ar' => 'رواندا', 'name_en' => 'Rwanda'],
    ['iso' => 'SN', 'dial' => '+221', 'name_ar' => 'السنغال', 'name_en' => 'Senegal'],
    ['iso' => 'CI', 'dial' => '+225', 'name_ar' => 'ساحل العاج', 'name_en' => 'Ivory Coast'],
    ['iso' => 'CM', 'dial' => '+237', 'name_ar' => 'الكاميرون', 'name_en' => 'Cameroon'],
    ['iso' => 'ML', 'dial' => '+223', 'name_ar' => 'مالي', 'name_en' => 'Mali'],
    ['iso' => 'ZM', 'dial' => '+260', 'name_ar' => 'زامبيا', 'name_en' => 'Zambia'],
    ['iso' => 'ZW', 'dial' => '+263', 'name_ar' => 'زيمبابوي', 'name_en' => 'Zimbabwe'],
    ['iso' => 'MZ', 'dial' => '+258', 'name_ar' => 'موزمبيق', 'name_en' => 'Mozambique'],
    ['iso' => 'AO', 'dial' => '+244', 'name_ar' => 'أنغولا', 'name_en' => 'Angola'],
    ['iso' => 'NA', 'dial' => '+264', 'name_ar' => 'ناميبيا', 'name_en' => 'Namibia'],
    ['iso' => 'BW', 'dial' => '+267', 'name_ar' => 'بوتسوانا', 'name_en' => 'Botswana'],
    ['iso' => 'MU', 'dial' => '+230', 'name_ar' => 'موريشيوس', 'name_en' => 'Mauritius'],
    ['iso' => 'MX', 'dial' => '+52', 'name_ar' => 'المكسيك', 'name_en' => 'Mexico'],
    ['iso' => 'BR', 'dial' => '+55', 'name_ar' => 'البرازيل', 'name_en' => 'Brazil'],
    ['iso' => 'AR', 'dial' => '+54', 'name_ar' => 'الأرجنتين', 'name_en' => 'Argentina'],
    ['iso' => 'CL', 'dial' => '+56', 'name_ar' => 'تشيلي', 'name_en' => 'Chile'],
    ['iso' => 'CO', 'dial' => '+57', 'name_ar' => 'كولومبيا', 'name_en' => 'Colombia'],
    ['iso' => 'PE', 'dial' => '+51', 'name_ar' => 'بيرو', 'name_en' => 'Peru'],
    ['iso' => 'VE', 'dial' => '+58', 'name_ar' => 'فنزويلا', 'name_en' => 'Venezuela'],
    ['iso' => 'EC', 'dial' => '+593', 'name_ar' => 'الإكوادور', 'name_en' => 'Ecuador'],
    ['iso' => 'BO', 'dial' => '+591', 'name_ar' => 'بوليفيا', 'name_en' => 'Bolivia'],
    ['iso' => 'PY', 'dial' => '+595', 'name_ar' => 'باراغواي', 'name_en' => 'Paraguay'],
    ['iso' => 'UY', 'dial' => '+598', 'name_ar' => 'أوروغواي', 'name_en' => 'Uruguay'],
    ['iso' => 'PA', 'dial' => '+507', 'name_ar' => 'بنما', 'name_en' => 'Panama'],
    ['iso' => 'CR', 'dial' => '+506', 'name_ar' => 'كوستاريكا', 'name_en' => 'Costa Rica'],
    ['iso' => 'GT', 'dial' => '+502', 'name_ar' => 'غواتيمالا', 'name_en' => 'Guatemala'],
    ['iso' => 'HN', 'dial' => '+504', 'name_ar' => 'هندوراس', 'name_en' => 'Honduras'],
    ['iso' => 'SV', 'dial' => '+503', 'name_ar' => 'السلفادور', 'name_en' => 'El Salvador'],
    ['iso' => 'NI', 'dial' => '+505', 'name_ar' => 'نيكاراغوا', 'name_en' => 'Nicaragua'],
    ['iso' => 'CU', 'dial' => '+53', 'name_ar' => 'كوبا', 'name_en' => 'Cuba'],
    ['iso' => 'DO', 'dial' => '+1', 'name_ar' => 'جمهورية الدومينيكان', 'name_en' => 'Dominican Republic'],
    ['iso' => 'JM', 'dial' => '+1', 'name_ar' => 'جامايكا', 'name_en' => 'Jamaica'],
    ['iso' => 'HT', 'dial' => '+509', 'name_ar' => 'هايتي', 'name_en' => 'Haiti'],
    ['iso' => 'IL', 'dial' => '+972', 'name_ar' => 'إسرائيل', 'name_en' => 'Israel'],
];
